//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTaskTracker.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Property : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string v)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
            {
                handler(this, new PropertyChangedEventArgs(v));

            }
        }

        public long Id { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> ClockIn { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> LastClosed { get; set; }
        private Nullable<double> _selected;
        public Nullable<double> Selected
        {
            get
            {
                return _selected;
            }

            set
            {
                _selected = value;
                OnPropertyChanged("Selected");
            }
        }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> Seconds { get; set; }
    }
}
